### ISSUE TITLE
Internal redirect algorithm clarification

### ISSUE THREAD

**Issue by iNDicat0r** [flygoast/ngx_http_internal_redirect#2]
Hi
First of all thank you for your library.

I need some clarification on the way this lib works. So lets say i am uploading data to a location /photo/upload.

Now i have 2 internal location one called /photo/multipartupload and other /photo/clientbodyonly. When request is coming to the server a custom header is passed by the client, and based on this custom header the location '/photo/upload' should redirect the users to those internal location.

The question is, does the upload data first go through '/photo/upload' location and when the request is finished uploading the data, the redirect is done again with the same data to the new location?  if this is the case then we are talking about very poor performance and arch design.

The best scenario is to do the internal redirect instantly and that internal location handle all the uploading. Please do clarify.

Regards

**Comment by flygoast** [comment]
The module handler is registered at 'REWRITE' phase, it would not read the request body. You can have a try.

**Comment by iNDicat0r** [comment]
Very well. I will try it now. Just a question, isn't it possible to achieve this conditional internal redirect with standard nginx?

**Comment by iNDicat0r** [comment]
One more thing, having this:

`location /redirect {
	
        internal_redirect_if ($HTTP_UPLOAD_METHOD = 'body' ) @foo;
	internal_redirect_if ($HTTP_UPLOAD_METHOD = 'multipart') @bar;
     
    }`

how should i return an http error( 405 for example) if $HTTP_UPLOAD_METHOD is not set or is empty ? is there any 'if-else' kind of mechanism to achieve this ?

**Comment by flygoast** [comment]
When I wrote the module, I didn't find the a method to a good method to complete a flexible internal redirect.  Only `return` or `error_page` can be used. For the 'if-else' case, maybe you can use Lua to  solve. Use `ngx_lua` or directly use `openresty`: http://openresty.org.

**Comment by iNDicat0r** [comment]
Thank you i appreciate your help. Closing this issue now unless i discover anything new.
Have a nice day.
